export { default as Ecommerce } from './Ecommerce'
export { default as Analytics } from './Analytics'
export { default as NavbarHorizontal } from './NavbarHorizontal'
export { default as NavbarVertical } from './NavbarVertical'
export { default as Login } from './Login'
export { default as CRM } from './CRM'
export { default as BillManagement } from './BillManagement'
export { AddProduct, EditProduct } from './ConfigProduct'
export { default as ProductManagement } from './ProductManagement'
