export { default as Ecommerce } from './Ecommerce'
export { default as Analytics } from './Analytics'
export { default as NavbarHorizontal } from './NavbarHorizontal'
export { default as NavbarVertical } from './NavbarVertical'
export { default as Login } from './Login'
export { default as CRM } from './CRM'
export { default as BillManagement } from './BillManagement'
export { default as ProductManagement } from './ProductManagement'
export { default as AddProduct } from './ProductManagement/add'
export { default as EditProduct } from './ProductManagement/edit'
export { default as Accounts } from './Accounts'
export { EditAccount, AddAccount } from './ConfigAccount'
